### ISSUE TITLE
Create GitHub page for the project

### ISSUE THREAD

**Issue by bronzdoc** [fastruby/skunk#49]
It would be nice that the project have a [Github page](https://pages.github.com/) so users know more about skunk in a more presentable way.

The first version of this page will be basically the Readme adapted as a website.

> NOTE: Design of the page will be provided by the Skunk team

Examples:
 - https://serverspec.org/
 - https://bundler.io/

**Comment by joshi008** [comment]
Hi, Could I take the issue and start working on it. I would be happy for my first open source contribution. :)

**Comment by etagwerker** [comment]
@joshi008 Yes, that would be great! You could re-use the design that has been implemented in this GitHub Page: 

- https://fastruby.github.io/styleguide/ (source here: https://github.com/fastruby/styleguide)

**Comment by joshi008** [comment]
Just made a simple page containing Readme file at https://joshi008.github.io/skunk/
The source code for the page is at:  https://github.com/joshi008/skunk/tree/gh-pages
The jekyll source code of the page at: https://github.com/joshi008/skunk/tree/jekyll-page

Currently the page needs more styling and many other things, do give feedback.

Why used jekyll?
At later stage this could be helpful for releasing the versions of software due to the post system in Jekyll.

**Comment by rdormer** [comment]
@joshi008 Thank you so much for this :). I've pushed the jekyll-page branch to a github pages repository for fastruby.io - I expect that we'll be moving the page to a subdirectory shortly, but it's live.

**Comment by rdormer** [comment]
Page is now live at https://fastruby.github.io/skunk/
